base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

APP_NAME = ''

urlpatterns = [
    path('', views.index, name="main"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('qna/', include('questions.urls')),
    path('admin/', admin.site.urls),
    ## path('find_username/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('list/', views.list, name='list'),
    path('delete/<int:cart_item_id>/', views.delete, name='delete'),
    path('modify/<int:cart_item_id>/', views.modify, name='modify'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:product_id>/', views.product_detail, name='detail'),
    path('<int:product_id>/question/create/', views.question_create, name='question_create'),
    path('<int:product_id>/question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    path('<int:product_id>/question/modify/<int:question_id>', views.question_modify, name='question_modify'),
]

cart/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from accounts.models import User
from products.models import ProductReal


class CartItem(models.Model):
    reg_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_real = models.ForeignKey(ProductReal, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField('수량', default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    validators = [MinValueValidator(1), MaxValueValidator(100)]

cart/forms.py
from django.forms import ModelForm

from cart.models import CartItem
from products.models import ProductReal


class ProductCartAddForm(ModelForm):
    def __init__(self, *args, **kwargs):
        product_id: int = kwargs['product_id'] if 'product_id' in kwargs.keys() else 0
        if product_id:
            del kwargs['product_id']
        super().__init__(*args, **kwargs)
        self.fields['product_real'].label = "옵션"

        if product_id:
            product_reals = ProductReal.objects.filter(product_id=product_id)
            product_real_choices = [(i.id, f'{i.option_1_display_name} / {i.option_2_display_name}') for i in
                                    product_reals]

            self.fields['product_real'].choices = product_real_choices

    class Meta:
        model = CartItem
        fields = ['product_real', 'quantity']

cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import QuerySet
from django.http import HttpRequest

# Create your views here.
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST, require_GET

from cart.forms import ProductCartAddForm
from cart.models import CartItem
from products.models import ProductReal


@login_required
@require_POST
def add(request: HttpRequest):
    product_real: ProductReal = ProductReal.objects.get(id=request.POST.get('product_real'))
    form = ProductCartAddForm(request.POST)

    if form.is_valid():
        cart_items_qs:QuerySet = CartItem.objects.filter(user=request.user, product_real = product_real)

        if cart_items_qs.exists():
            old_cart_item = cart_items_qs.first()
            old_cart_item.quantity += int(form.cleaned_data['quantity'])
            old_cart_item.save()
        else:
            cart_item = form.save(commit=False)
            cart_item.user = request.user
            cart_item.save()

        messages.success(request, "장바구니에 추가되었습니다.")
        return redirect('products:detail', product_real.product.id)

    messages.error(request, form['quantity'].errors, 'danger')
    return redirect('products:detail', product_real.product.id)


@login_required
@require_GET
def list(request: HttpRequest):
    cart_items = CartItem.objects.filter(user=request.user)

    return render(request, "cart/list.html", {
        "cart_items": cart_items
    })

@login_required
@require_POST
def delete_items(request: HttpRequest):
    ids = map(int, request.POST.get('ids').split(','))
    cart_items = CartItem.objects.filter(id__in=ids)

    for cart_item in cart_items:
        if cart_item.user != request.user:
            raise PermissionError()
        cart_item.delete()

    messages.success(request, "해당 장바구니 품목들이 삭제되었습니다.")

    return redirect('cart:list')

@login_required
@require_GET
def delete(request: HttpRequest, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)

    if cart_item.user != request.user:
        raise PermissionError()

    cart_item.delete()

    messages.success(request, "해당 장바구니 품목이 삭제되었습니다.")

    return redirect('cart:list')


@login_required
@require_POST
def modify(request: HttpRequest, cart_item_id):
    cart_item = get_object_or_404(CartItem, id=cart_item_id)

    if cart_item.user != request.user:
        raise PermissionError()

    cart_item.quantity = int(request.POST.get('quantity'))
    cart_item.save()

    messages.success(request, "해당 장바구니 품목의 개수가 수정되었습니다.")

    return redirect('cart:list')

cart/templates/cart/list.html
{% extends "layout.html" %}
{% load humanize %}

{%block content %}

<script>
    function CartItemModifyForm__updateQuantity(el, add) {
        const $form = $(el).closest('form');

        const $salePrice = $form.find('.cart-item-modify-form__sale-price');
        const productSalePrice = parseInt($salePrice.attr('data-sale-price'));
        const $inputNumber = $form.find('input[type="number"]');
        const oldQuantity = parseInt($inputNumber.val());
        let newQuantity = oldQuantity + add;

        if ( newQuantity > 100 ) {
            newQuantity = 100;
        }
        else if ( newQuantity < 1 ) {
            newQuantity = 1
        }

        $inputNumber.val(newQuantity);
        $salePrice.text((productSalePrice * newQuantity).price_format());
    }

    function CartItems__allCheckBoxCheckChanged(el) {
        if ( el.checked ) {
            $('.cart-items__checkbox-item:not(:checked)').prop('checked', true);
        }
        else {
            $('.cart-items__checkbox-item:checked').prop('checked', false);
        }
    }

    function CartItems__itemCheckeChanged(el) {
        const allCheckBoxNewCheckStatus = $('.cart-items__checkbox-item:not(:checked)').length == 0;
        $('.cart-items__checkbox-all').prop('checked', allCheckBoxNewCheckStatus);
    }

    function CartItems__deleteChecked() {
        const cartItemIds = $('.cart-items__checkbox-item:checked')
            .map((i, el) => parseInt($(el).attr('data-id')))
            .toArray();

        CartItemsDeleteForm.ids.value = cartItemIds;
        CartItemsDeleteForm.submit();
    }

</script>

<section class="section-cart-item-list">
    <div class="container">
        <h1 class="t-text-[1.2rem] t-font-bold">장바구니</h1>

        <div class="t-mt-[10px]">
            <input type="checkbox" class="cart-items__checkbox-all" onchange="CartItems__allCheckBoxCheckChanged(this)">
        </div>

        <ul>
            {% for cart_item in cart_items %}
            <li class="t-border-[color:#989898] t-border-0 t-border-t t-border-solid t-py-[20px]">
                <div class="t-flex">
                    <input data-id="{{cart_item.id}}" type="checkbox" class="cart-items__checkbox-item" onchange="CartItems__itemCheckeChanged(this)">
                    <a href="{% url 'products:detail' cart_item.product_real.product.id %}">
                        <img class="t-flex-shrink-0 t-ml-2 t-w-[80px] t-h-[80px] sm:t-w-[150px] sm:t-h-[150px] t-object-cover rounded"
                             src="{{cart_item.product_real.product.thumb_img_url}}" alt="">
                    </a>
                    <div class="t-ml-2"><a href="{% url 'products:detail' cart_item.product_real.product.id %}">{{cart_item.product_real.product.display_name}}</a>
                    </div>
                </div>
                <div class="t-flex t-pl-5 t-mt-2">
                    <div>{{cart_item.product_real.option_1_display_name}}</div>
                    <div>/</div>
                    <div>{{cart_item.product_real.option_2_display_name}}</div>
                </div>
                <div class="t-flex t-pl-5 t-mt-2">
                    <div>\ {{ cart_item.product_real.product.sale_price|intcomma }}</div>
                </div>
                <form method="POST" action="{% url 'cart:modify' cart_item.id %}"
                      class="t-flex t-items-center t-pl-5 t-mt-2">
                    {% csrf_token %}
                    <span onclick="CartItemModifyForm__updateQuantity(this, -1)">
                        <i class="fas fa-minus-circle"></i>
                    </span>
                    <span>&nbsp;</span>
                    <input name="quantity" readonly min="1" max="100" class="form-control t-w-[100px]" type="number"
                           value="{{cart_item.quantity}}">
                    <span>&nbsp;</span>
                    <span onclick="CartItemModifyForm__updateQuantity(this, 1)">
                        <i class="fas fa-plus-circle"></i>
                    </span>
                    <span>&nbsp;</span>
                    <input type="submit" class="btn btn-primary btn-sm" value="수량수정">
                    <span>&nbsp;</span>
                    <a onclick="if ( !confirm('정말 삭제하시겠습니까?') ) return false;"
                       href="{% url 'cart:delete' cart_item.id %}" class="btn btn-danger btn-sm">삭제</a>
                    <div class="t-flex-1"></div>
                    <div>
                        총 가격 :
                        \
                        {% widthratio cart_item.quantity 1 cart_item.product_real.product.sale_price as total_price %}
                        <span class="cart-item-modify-form__sale-price"
                              data-sale-price="{{cart_item.product_real.product.sale_price}}">{{total_price|intcomma}}</span>
                    </div>
                </form>
                <div>

                </div>
                <div>

                </div>
            </li>
            {% endfor %}
        </ul>

        <div>
            <button type="button" class="btn btn-danger btn-sm" onclick="CartItems__deleteChecked();">선택삭제</button>
        </div>

        <form name="CartItemsDeleteForm" class="t-hidden" action="{% url 'cart:delete_items' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="ids" value="">
        </form>
    </div>
</section>

{%endblock%}