accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('find_username/', views.find_username, name='find_username'),
    path('signin/kakao/', views.kakao_login, name="kakao_signin"),
    path('signin/kakao/callback/', views.kakao_login_callback, name="kakao_signin_callback"),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

APP_NAME = ''

urlpatterns = [
    path('', views.index, name="main"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('qna/', include('questions.urls')),
    path('admin/', admin.site.urls),
    ## path('find_username/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth import login
from django.contrib.auth.models import AbstractUser
# Create your models here.
from django.db import models
from django.db.models import QuerySet
from django.http import HttpRequest


class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"

    class ProviderTypeCodeChoices(models.TextChoices):
        LOCAL = "local", "로컬"
        KAKAO = "kakao", "카카오"

    gender = models.CharField('성별', max_length=1, blank=True, choices=GenderChoices.choices)
    avatar = models.ImageField('아바타', blank=True, upload_to="accounts/avatar/%Y/%m/%d",
                               help_text="100px * 100px 크기의 gif/png/jpg 이미지를 업로드해주세요.")
    provider_type_code = models.CharField('프로바이더 타입코드', max_length=20, choices=ProviderTypeCodeChoices.choices,
                                          default=ProviderTypeCodeChoices.LOCAL)
    provider_accounts_id = models.PositiveIntegerField('프로바이더 회원번호', default=0)

    @staticmethod
    def login_with_kakao(request: HttpRequest, provider_accounts_id):
        provider_type_code = User.ProviderTypeCodeChoices.KAKAO
        qs: QuerySet = User.objects.filter(provider_type_code=provider_type_code,
                                           provider_accounts_id=provider_accounts_id)

        if not qs.exists():
            username = provider_type_code + "__" + str(provider_accounts_id)
            name = provider_type_code + "__" + str(provider_accounts_id)
            email = ""
            password = ""
            user: User = User.objects.create_user(username=username, email=email, password=password, first_name=name,
                                                  provider_type_code=provider_type_code,
                                                  provider_accounts_id=provider_accounts_id)
        else:
            user: User = qs.first()

        login(request, user)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from accounts.models import User





class FindUsernameForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True

    class Meta:
        model = User
        fields = ['first_name', 'email']


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['first_name'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'first_name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

accounts/views.py
import os

from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.views import (
    logout_then_login, LoginView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.sites import requests
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse

from .decorators import logout_required
from .forms import SignupForm, FindUsernameForm
from .models import User
import requests
from lazy_string import LazyString


def kakao_login(request: HttpRequest):
    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")
    return redirect(
        f"https://kauth.kakao.com/oauth/authorize?client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&response_type=code"
    )


def kakao_login_callback(request):
    code = request.GET.get("code")
    REST_API_KEY = os.environ.get("KAKAO_APP__REST_API_KEY")
    REDIRECT_URI = os.environ.get("KAKAO_APP__LOGIN__REDIRECT_URI")

    token_request = requests.get(
        f"https://kauth.kakao.com/oauth/token?grant_type=authorization_code&client_id={REST_API_KEY}&redirect_uri={REDIRECT_URI}&code={code}"
    )

    token_json = token_request.json()

    error = token_json.get("error", None)
    if error is not None:
        raise Exception("카카오 로그인 에러")

    access_token = token_json.get("access_token")

    profile_request = requests.get(
        "https://kapi.kakao.com/v2/user/me",
        headers={"Authorization": f"Bearer {access_token}"},
    )
    profile_json = profile_request.json()

    id = profile_json.get("id")

    User.login_with_kakao(request, id)

    messages.success(request, "카카오톡 계정으로 로그인되었습니다")

    return redirect("main")


class MyLoginView(SuccessMessageMixin, LoginView):
    template_name = "accounts/signin.html"
    next_page = "/"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.success_message = LazyString(
            lambda: f'{self.request.user.last_name}{self.request.user.first_name}님 환영합니다.')

    def get_initial(self):
        initial = self.initial.copy()
        initial['username'] = self.request.GET.get('username', None)

        return initial



@logout_required
def signin(request: HttpRequest):
    return LoginView.as_view(template_name="accounts/signin.html")(request)


def signout(request: HttpRequest):
    messages.success(request, "로그아웃 되었습니다.")
    return logout_then_login(request)


@logout_required
def signup(request: HttpRequest):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            signed_user = form.save()
            auth_login(request, signed_user)
            messages.success(request, "회원가입 환영합니다.")
            # signed_user.send_welcome_email()
            next_url = request.GET.get('next', '/')
            return redirect(next_url)
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })


def find_username(request: HttpRequest):
    if request.method == 'POST':
        form = FindUsernameForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            first_name = form.cleaned_data['first_name']

            qs: QuerySet = User.objects.filter(email=email, first_name=first_name)

            if not qs.exists():
                messages.warning(request, "일치하는 회원이 존재하지 않습니다.")
            else:
                user: User = qs.first()
                messages.success(request, f"해당회원의 username은 {user.username} 입니다.")
                return redirect(reverse("accounts:signin") + '?username=' + user.username)
    else:
        form = FindUsernameForm()

    return render(request, 'accounts/find_username.html', {
        'form': form,
    })

accounts/templates/accounts/find_username.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}

<section class="section-signup t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header">아이디찾기</div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="아이디찾기" %}
                {% bootstrap_button button_type="reset" content="취소" %}
            </form>
        </div>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/find_usernameForm.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}

<section class="section-signup t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header">아이디찾기</div>
        <div class="card-body">
            <form method="POST">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="아이디찾기" %}
                {% bootstrap_button button_type="reset" content="취소" %}
            </form>
        </div>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/signin.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}
<section class="section-signin t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header">로그인</div>
        <div class="card-body">
            <form method="POST" action="">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="로그인" %}
                {% bootstrap_button button_type="reset" content="취소" %}
            </form>
            <hr>
            <a href="{% url 'accounts:kakao_signin' %}">카카오로 로그인</a>
        </div>
    </div>
</section>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block content %}
<section class="section-signup t-flex-1 t-flex t-items-center t-justify-center">
    <div class="card t-w-full t-max-w-screen-md mx-4">
        <div class="card-header">회원가입</div>
        <div class="card-body">
            <form method="POST" action="">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% bootstrap_button button_type="submit" content="회원가입" %}
                {% bootstrap_button button_type="reset" content="취소" %}
            </form>
        </div>
    </div>
</section>
{% endblock %}