accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('find_username/', views.find_username, name='find_username'),
    path('signin/kakao/', views.kakao_login, name="kakao_signin"),
    path('signin/kakao/callback/', views.kakao_login_callback, name="kakao_signin_callback"),
]

base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views

APP_NAME = ''

urlpatterns = [
    path('', views.index, name="main"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('qna/', include('questions.urls')),
    path('admin/', admin.site.urls),
    ## path('find_username/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('list/', views.list, name='list'),
    path('delete/<int:cart_item_id>/', views.delete, name='delete'),
    path('modify/<int:cart_item_id>/', views.modify, name='modify'),
    path('delete_items/', views.delete_items, name='delete_items'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:product_id>/', views.product_detail, name='detail'),
    path('<int:product_id>/question/create/', views.question_create, name='question_create'),
    path('<int:product_id>/question/delete/<int:question_id>', views.question_delete, name='question_delete'),
    path('<int:product_id>/question/modify/<int:question_id>', views.question_modify, name='question_modify'),
]

products/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation

# Create your models here.
from markets.models import Market
from questions.models import Question

class ProductCategory(models.Model):
    name = models.CharField('이름', max_length=50)

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    is_deleted = models.BooleanField('삭제여부', default=False)
    delete_date = models.DateTimeField('삭제날짜', null=True, blank=True)
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)
    name = models.CharField('상품명(내부용)', max_length=100)
    display_name = models.CharField('상품명(고객용)', max_length=100)
    price = models.PositiveIntegerField('권장판매가')
    sale_price = models.PositiveIntegerField('실제판매가')
    is_hidden = models.BooleanField('노출여부', default=False)
    is_sold_out = models.BooleanField('품절여부', default=False)
    category = models.ForeignKey(ProductCategory, on_delete=models.DO_NOTHING)
    hit_count = models.PositiveIntegerField('조회수', default=0)
    review_count = models.PositiveIntegerField('리뷰수', default=0)
    review_point = models.PositiveIntegerField('리뷰평점', default=0)
    questions = GenericRelation(Question, related_query_name="question")

    def thumb_img_url(self):

        img_name = self.category.name
        img_name += '2' if self.id % 2 == 0 else ''
        return f"https://raw.githubusercontent.com/jhs512/mbly-img/master/{img_name}.jpg"

    def colors(self):
        colors = []
        product_reals = self.product_reals.all()
        for product_real in product_reals:
            colors.append(product_real.option_2_name)

        html = ''

        for color in set(colors):
            if color == '레드':
                rgb_color = 'red'
            elif color == '그린':
                rgb_color = 'green'
            elif color == '블루':
                rgb_color = 'blue'
            elif color == '핑크':
                rgb_color = 'pink'
            elif color == '와인':
                rgb_color = '#722F37'
            html += f"""<span style="width:10px; height:10px; display:inline-block; border-radius:50%; margin:0 3px; background-color:{rgb_color};"></span>"""

        return html


class ProductReal(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_reals")
    option_1_type = models.CharField('옵션1 타입', max_length=10, default='SIZE')
    option_1_name = models.CharField('옵션1 이름(내부용)', max_length=50)
    option_1_display_name = models.CharField('옵션1 이름(고객용)', max_length=50)
    option_2_type = models.CharField('옵션2 타입', max_length=10, default='COLOR')
    option_2_name = models.CharField('옵션2 이름(내부용)', max_length=50)
    option_2_display_name = models.CharField('옵션2 이름(고객용)', max_length=50)
    option_3_type = models.CharField('옵션3 타입', max_length=10, default='', blank=True)
    option_3_name = models.CharField('옵션3 이름(내부용)', max_length=50, default='', blank=True)
    option_3_display_name = models.CharField('옵션3 이름(고객용)', max_length=50, default='', blank=True)
    is_sold_out = models.BooleanField('품절여부', default=False)
    is_hidden = models.BooleanField('노출여부', default=False)
    add_price = models.IntegerField('추가가격', default=0)
    stock_quantity = models.PositiveIntegerField('재고개수, 품절일때 유용함', default=0)

products/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core import exceptions
from django.core.paginator import Paginator
from django.http import HttpRequest
from django.shortcuts import render, get_object_or_404, redirect

from cart.forms import ProductCartAddForm
from products.models import Product
from questions.forms import QuestionForm
from questions.models import Question


def product_list(request: HttpRequest):
    search_keyword = request.GET.get('search_keyword', '')
    page = request.GET.get('page', '1')

    if not search_keyword:
        products = Product.objects.order_by('-id')
    else:
        products = Product.objects.filter(display_name__icontains=search_keyword).order_by('-id')

    paginator = Paginator(products, 4)  # 페이지당 10개씩 보여주기
    products = paginator.get_page(page)

    return render(request, "products/product_list.html", {
        "products": products
    })


def _product_detail(request: HttpRequest, product_id):
    cart_add_form = ProductCartAddForm(product_id=product_id)

    product = get_object_or_404(Product, id=product_id)

    if request.method == "POST" and request.user.is_authenticated:
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.content_type = ContentType.objects.get_for_model(product)
            question.object_id = product.id
            question.user = request.user
            question.save()
            messages.success(request, "질문이 등록되었습니다.")

            return redirect("products:detail", product_id=product.id)
    else:
        form = QuestionForm()

        form.errors

    product_reals = product.product_reals.order_by('option_1_display_name', 'option_2_display_name')
    questions = product.questions.order_by('-id')

    return render(request, "products/product_detail.html", {
        "product": product,
        "product_reals": product_reals,
        "questions": questions,
        "question_form": form,
        "cart_add_form": cart_add_form,
    })


def product_detail(request: HttpRequest, product_id):
    return _product_detail(request, product_id)


def question_create(request: HttpRequest, product_id):
    return _product_detail(request, product_id)


@login_required
def question_delete(request: HttpRequest, product_id, question_id):
    question = get_object_or_404(Question, id=question_id)

    if request.user != question.user:
        raise exceptions.PermissionDenied()

    question.delete()

    messages.success(request, "질문이 삭제되었습니다.")

    return redirect("products:detail", product_id=product_id)


def question_modify(request: HttpRequest, product_id, question_id):
    product = get_object_or_404(Product, id=product_id)
    question = get_object_or_404(Question, id=question_id)

    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)

        if form.is_valid():
            form.save()
            messages.success(request, "질문이 수정되었습니다.")
            return redirect("products:detail", product_id=product_id)
    else:
        form = QuestionForm(None, instance=question)

    return render(request, "products/question_modify.html", {
        "product": product,
        "question": question,
        "question_form": form,
    })

products/templates/products/product_detail.html
{% extends "layout.html" %}
{% load humanize %}
{% load django_bootstrap5 %}

{%block content %}

<section class="section-prod-detail">
    <div class="container">
        <div class="card">
            <div class="card-header">
                상품상세정보
            </div>

            <ul class="list-group list-group-flush">
                <li class="list-group-item">
                    <img class="t-w-full t-max-w-[300px] t-rounded" src="{{product.thumb_img_url}}" alt="">
                </li>
                <li class="list-group-item">
                    <span class="t-w-16 t-inline-block">번호</span>
                    <span class="badge bg-primary">{{product.id}}</span>
                </li>
                <li class="list-group-item">
                    <span class="t-w-16 t-inline-block">마켓</span>
                    <span class="badge bg-primary">{{product.market.name}}</span>
                </li>
                <li class="list-group-item">
                    <span class="t-w-16 t-inline-block">상품명</span>
                    <span class="t-font-bold">{{product.display_name}}</span>
                </li>
                <li class="list-group-item">
                    <span class="t-w-16 t-inline-block">가격</span>
                    <span class="t-font-bold">{{product.sale_price|intcomma}}</span>원
                </li>
            </ul>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                장바구니 담기
            </div>

            <div class="card-body">
                <form action="{% url 'cart:add' %}" method="POST">
                    {% csrf_token %}
                    {% bootstrap_form cart_add_form %}
                    {% bootstrap_button button_type="submit" content="장바구니 담기" %}
                    {% bootstrap_button button_type="reset" content="취소" %}
                </form>
            </div>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                옵션
            </div>

            <div class="card-body">
                <table class="table table-hover">
                    <colgroup>
                        <col class="sm:t-w-40">
                        <col class="sm:t-w-40">
                        <col>
                    </colgroup>
                    <thead>
                    <tr>
                        <th>사이즈</th>
                        <th>색상</th>
                        <th>품절</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for product_real in product_reals %}
                    <tr>
                        <td>
                            {{product_real.option_1_display_name}}
                        </td>
                        <td>
                            {{product_real.option_2_display_name}}
                        </td>
                        <td>
                            {% if not product_real.is_sold_out %}
                            <span class="badge bg-primary">판매중</span>
                            {% else %}
                            <span class="badge bg-secondary">품절</span>
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                질문등록
            </div>

            <div class="card-body">
                {% if user.is_authenticated %}

                <form method="POST" action="{% url 'products:question_create' product.id %}">
                    {% csrf_token %}

                    {% bootstrap_form question_form %}
                    {% bootstrap_button button_type="submit" content="질문작성" %}
                    {% bootstrap_button button_type="reset" content="취소" %}

                </form>
                {% else %}
                <div class="t-text-gray-400">
                    <a href="{% url 'accounts:signin' %}?next={{request.get_full_path}}">로그인</a> 후 이용해주세요.
                </div>
                {% endif %}

                {% if question_form.errors %}
                <script>
                    let $lastForm = $('form').last();
                    $(window).on('load', function() {
                        $(window).scrollTop($lastForm.offset().top);
                    });


                </script>
                {% endif %}

            </div>
        </div>

        <div class="card t-mt-[30px]">
            <div class="card-header">
                질문리스트
            </div>

            {% if questions %}
            <ul class="list-group list-group-flush">
                {% for question in questions %}
                <li class="list-group-item">
                    <span class="badge bg-secondary">{{question.id}}</span>
                    {{question.body}}
                    {% if question.user == request.user %}
                    <a href="{% url 'products:question_delete' product.id question.id %}" class="btn btn-sm btn-warning"
                       onclick="if ( confirm('정말 삭제하시겠습니까?') == false ) return false;">삭제</a>
                    {% endif %}
                    <a href="{% url 'products:question_modify' product.id question.id %}"
                       class="btn btn-sm btn-secondary">수정</a>
                </li>
                {% endfor %}
            </ul>
            {% endif %}

            {% if not questions %}
            <div class="card-body">
                <div class="t-text-gray-400">
                    질문이 없습니다.
                </div>
            </div>
            {% endif %}
        </div>

    </div>
</section>
{%endblock%}

products/templates/products/product_list.html
{% extends "layout.html" %}
{% load humanize %}

{%block content %}
{% with img_box_class="t-relative t-overflow-hidden t-rounded" %}
{% with img_box_before_class="before:t-content-[''] before:t-absolute before:t-inset-0 before:t-bg-[#00000000] group-hover:before:t-bg-[#00000055] before:t-transition-all" %}
{% with img_box_after_class="after:t-content-[attr(data-before)] after:t-hidden group-hover:after:t-block after:t-no-underline after:t-text-white after:t-border-2 after:t-border-white after:t-border-solid after:t-rounded after:t-p-2 after:t-whitespace-nowrap after:t-absolute after:t-top-[50%] after:t-left-[50%] after:t-translate-y-[-50%] after:t-translate-x-[-50%] after:t-transition-all" %}

<section class="section-prod-list">
    <div class="container">
        <h1 class="t-text-[1.2rem] t-font-bold">최신 상품리스트</h1>

        <ul class="t-grid t-grid-cols-1 sm:t-grid-cols-2 md:t-grid-cols-3 lg:sm:t-grid-cols-4 t-gap-[20px] t-mt-3">
            {% for product in products %}
            <li class="t-flex t-flex-col t-group">
                <a data-before="VIEW MORE" href="{% url 'products:detail' product.id %}"
                   class="{{img_box_class}} {{img_box_before_class}} {{img_box_after_class}}">
                    <img class="t-block t-w-full t-transition-all group-hover:t-scale-110 t-relative t--z-50 t-object-cover"
                         src="{{product.thumb_img_url}}" alt="" style="aspect-ratio: 1 / 1;">
                </a>
                <a class="t-text-center t-mt-2 t-no-underline t-text-black t-italic group-hover:t-underline"
                   href="{% url 'products:detail' product.id %}">
                    {{product.display_name}}
                </a>
                <a class="t-text-center t-mt-2 t-no-underline t-text-gray-400 group-hover:t-text-blue-500"
                   href="{% url 'products:detail' product.id %}">
                    <i class="fas fa-won-sign"></i>
                    <span>{{ product.sale_price|intcomma }}</span>
                </a>
                <a class="t-text-center t-mt-2 t-no-underline t-text-gray-400 group-hover:t-text-blue-500"
                   href="{% url 'products:detail' product.id %}">
                    <span>{{ product.colors|safe }}</span>
                </a>
            </li>
            {% endfor %}
        </ul>

        <ul class="pagination justify-content-center t-mt-12">
            <!-- 이전페이지 -->
            {% if products.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.previous_page_number }}&search_keyword={{request.GET.search_keyword}}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in products.paginator.page_range %}
            {% if products.number|add:-5 <= page_number <= products.number|add:5 %}
            {% if page_number == products.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" href="?page={{ page_number }}&search_keyword={{request.GET.search_keyword}}">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ page_number }}&search_keyword={{request.GET.search_keyword}}">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if products.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ products.next_page_number }}&search_keyword={{request.GET.search_keyword}}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
    </div>
</section>
{% endwith %}
{% endwith %}
{% endwith %}

{%endblock%}

products/templates/products/question_modify.html
{% extends "layout.html" %}
{% load humanize %}
{% load django_bootstrap5 %}

{%block content %}
<section class="section-prod-question-modify mt-4">
    <div class="container">
        <h1>상품 기본정보</h1>
        <div>
            번호 : {{product.id}}
        </div>
        <div>
            등록 : {{product.reg_date}}
        </div>
        <div>
            수정 : {{product.update_date}}
        </div>
        <div>
            이름 : {{product.display_name}}
        </div>
        <div>
            가격 : {{product.sale_price}}원
        </div>
        <div>
            마켓 : {{product.market.name}}
        </div>

        <h1 class="mt-3">옵션</h1>
        <ul>
            {% for product_real in product_reals %}
            <li>
                {{product_real.option_1_type}} : {{product_real.option_1_display_name}}
                /
                {{product_real.option_2_type}} : {{product_real.option_2_display_name}}
            </li>
            {% endfor %}
        </ul>

        <h1 class="mt-3">질문 수정</h1>

        <form method="POST" action="{% url 'products:question_modify' product.id question.id %}">
            {% csrf_token %}

            {% bootstrap_form question_form %}
            {% bootstrap_button button_type="submit" content="질문수정" %}
            {% bootstrap_button button_type="reset" content="취소" %}

        </form>
    </div>
</section>
{%endblock%} 